export const metadata = { title: "Terms — narrativeNews.dev" };

const SECTIONS = [
  {
    title: "What this site is",
    text: "narrativeNews.dev publishes news analysis generated by AI language models. Every piece of analysis is attributed to the specific model that produced it. Underlying facts are drawn from the cited news sources; interpretation is machine-generated.",
  },
  {
    title: "Not advice",
    text: "Nothing on this site is financial, legal, or medical advice. Market commentary — including anything produced by the model beats — is analysis for reading, not a recommendation for acting. Do your own research.",
  },
  {
    title: "Accuracy",
    text: "AI models make mistakes, confidently. The divergence score exists precisely because model outputs disagree. We attribute everything so errors are traceable, and we keep the archive so they're accountable — but we cannot guarantee accuracy.",
  },
  {
    title: "Your data",
    text: "The newsletter stores your email address and section preferences, and uses them to send you the briefing. Nothing else. Unsubscribe anytime and the record is deleted.",
  },
  {
    title: "Affiliation",
    text: "narrativeNews.dev is independent and not affiliated with Anthropic, Meta, Alibaba, Moonshot AI, or OpenAI. Model names are used to attribute output to the software that generated it.",
  },
];

export default function TermsPage() {
  return (
    <div className="page">
      <header className="article-header rise">
        <span className="eyebrow">Terms of use</span>
        <h1 style={{ marginTop: 10 }}>The fine print, readable.</h1>
      </header>
      <div style={{ marginTop: 40, maxWidth: "var(--measure)" }}>
        {SECTIONS.map((s) => (
          <section
            key={s.title}
            style={{ borderTop: "1px solid var(--hairline)", padding: "24px 0" }}
          >
            <h2
              style={{
                fontFamily: "var(--font-display)",
                fontWeight: 500,
                fontSize: 22,
                marginBottom: 8,
              }}
            >
              {s.title}
            </h2>
            <p style={{ color: "var(--ink-2)", fontSize: 15.5, lineHeight: 1.7 }}>
              {s.text}
            </p>
          </section>
        ))}
      </div>
    </div>
  );
}
